lifecycle: fix behavior for core22-step-dependencies

diff --git a/tests/spread/general/core22-step-dependencies/task.yaml b/tests/spread/general/core22-step-dependencies/task.yaml
--- a/tests/spread/general/core22-step-dependencies/task.yaml
+++ b/tests/spread/general/core22-step-dependencies/task.yaml
@@ -13,3 +13,15 @@ execute: |
     echo "FAIL: staged files from part1 found"
     exit 1
   fi
+
+  # save the time of file left in first pulling
+  TIMESTAMP1=$(stat parts/part2/src/testfile --format=%y)
+
+  # now stage (which should NOT pull again, as part2 was already pulled)
+  snapcraft stage
+
+  TIMESTAMP2=$(stat parts/part2/src/testfile --format=%y)
+  if [ "$TIMESTAMP2" != "$TIMESTAMP1" ]; then
+    echo "FAIL: file timestamp is modified (part2 did a re-pull)"
+    exit 1
+  fi
