environment: error when build-for arch variable cannot be evaluated
For core20 snaps, if the project variable `SNAPCRAFT_ARCH_BUILD_FOR` or
`SNAPCRAFT_ARCH_TRIPLET_BUILD_FOR` cannot be determined and are used in
a snapcraft.yaml file, then an error is raised.

Signed-off-by: Callahan Kovacs <callahan.kovacs@canonical.com>

diff --git a/tests/spread/cross-compile/environment/task.yaml b/tests/spread/cross-compile/environment/task.yaml
--- a/tests/spread/cross-compile/environment/task.yaml
+++ b/tests/spread/cross-compile/environment/task.yaml
@@ -1,25 +1,41 @@
 summary: Test envvars related to architectures
 
 environment:
-  SNAP/build_for_single_arch: build-for-single-arch
   SNAP/build_for_multi_arch: build-for-multi-arch
+  SNAP/build_for_multi_arch_error: build-for-multi-arch-error
+  SNAP/build_for_multi_arch_triplet_error: build-for-multi-arch-triplet-error
+  SNAP/build_for_part_error: build-for-part-error
+  SNAP/build_for_part_triplet_error: build-for-part-triplet-error
+  SNAP/build_for_single_arch: build-for-single-arch
   SNAP/build_for_unknown_arch: build-for-unknown-arch
+  SNAP/build_for_unknown_arch_error: build-for-unknown-arch-error
+  SNAP/build_for_unknown_arch_triplet_error: build-for-unknown-arch-triplet-error
   SNAP/target_arch: target-arch
 
 restore: |
   cd "./snaps/$SNAP"
-  snapcraft clean
+  snapcraft clean --destructive-mode
   rm -f ./*.snap
 
 execute: |
   cd "./snaps/$SNAP"
 
+  # test error scenarios
+  if [[ $SNAP == *error* ]]; then
+    if snapcraft --destructive-mode; then
+      echo "snapcraft did not fail but should have"
+      exit 1
+    fi
+    exit 0
+  fi
+
+  # test successful scenarios
   if [ "${SNAP}" == "target-arch" ]; then
     snapcraft prime --destructive-mode --target-arch armhf --enable-experimental-target-arch
   else
     snapcraft prime --destructive-mode
   fi
-  
+
   while read -r expected_envvar; do
     if ! grep -qF "$expected_envvar" prime/meta/snap.yaml; then
       echo "Did not find '$expected_envvar' in 'prime/meta/snap.yaml'."
