tests: update kde extension spread task to account for content snaps
- Verify content snaps are installed.
- Verify there are no missing packages.

Signed-off-by: Chris Patterson <chris.patterson@canonical.com>

diff --git a/tests/spread/extensions/kde-neon/task.yaml b/tests/spread/extensions/kde-neon/task.yaml
--- a/tests/spread/extensions/kde-neon/task.yaml
+++ b/tests/spread/extensions/kde-neon/task.yaml
@@ -27,7 +27,7 @@ restore: |
 
 execute: |
   cd "$SNAP_DIR"
-  snapcraft
+  output="$(snapcraft)"
 
   sudo snap install neon-hello_*.snap --dangerous
 
@@ -42,3 +42,12 @@ execute: |
   [ -d "$snap_user_data/.local" ]
   [ -f "$snap_user_data/.last_revision" ]
   [ "$(cat "$snap_user_data/.last_revision")" = "SNAP_DESKTOP_LAST_REVISION=x1" ]
+
+  # Verify content snap was installed for dependency checks.
+  sudo snap list kde-frameworks-5-core18
+
+  # Verify all dependencies were found.
+  if echo "$output" | grep -q "part is missing libraries"; then
+    echo "failed to find content snaps' libraries"
+    exit 1
+  fi
