Update extensions/desktop/command-chain-kde/run
Improve error.

Co-authored-by: Alex Lowe <alex.lowe@canonical.com>

diff --git a/extensions/desktop/command-chain-kde/run b/extensions/desktop/command-chain-kde/run
--- a/extensions/desktop/command-chain-kde/run
+++ b/extensions/desktop/command-chain-kde/run
@@ -12,8 +12,8 @@ fi
 
 
 if [ ! -f "$1" ]; then
-  echo "Content snap command-chain for $1 not found: ensure slot is connected"
-  exit
+  >&2 echo "Content snap command-chain for $1 not found: ensure slot is connected"
+  exit 1
 fi
 
 # emulate "exec $@" using "source"
