test(spread): reorder task.yaml keys
Signed-off-by: Callahan Kovacs <callahan.kovacs@canonical.com>

diff --git a/tests/spread/_common/appstream-desktop/task.yaml b/tests/spread/_common/appstream-desktop/task.yaml
--- a/tests/spread/_common/appstream-desktop/task.yaml
+++ b/tests/spread/_common/appstream-desktop/task.yaml
@@ -10,14 +10,6 @@ systems:
   - ubuntu-24.04-64
   - ubuntu-24.04-amd64
 
-restore: |
-  cd "${SNAP}"
-  # The regular clean can potentially fail depending on if/when the test itself failed, but
-  # they should always both be attempted
-  snapcraft clean || true
-  snapcraft clean --destructive-mode
-  rm -f ./*.snap
-
 execute: |
   cd "${SNAP}"
 
@@ -36,3 +28,11 @@ execute: |
       echo "The formatting for appstream-desktop.desktop is incorrect"
       exit 1
   fi
+
+restore: |
+  cd "${SNAP}"
+  # The regular clean can potentially fail depending on if/when the test itself failed, but
+  # they should always both be attempted
+  snapcraft clean || true
+  snapcraft clean --destructive-mode
+  rm -f ./*.snap
diff --git a/tests/spread/_common/manifest-info-envvars/task.yaml b/tests/spread/_common/manifest-info-envvars/task.yaml
--- a/tests/spread/_common/manifest-info-envvars/task.yaml
+++ b/tests/spread/_common/manifest-info-envvars/task.yaml
@@ -6,14 +6,6 @@ systems:
 prepare: |
   snap install review-tools
 
-restore: |
-  # The regular clean can potentially fail depending on if/when the test itself failed, but
-  # they should always both be attempted
-  snapcraft clean || true
-  snapcraft clean --destructive-mode
-  rm -f ./*.snap
-  rm -f ~/manifest_0.1_*.snap
-
 execute: |
   export SNAPCRAFT_BUILD_INFO=1
   export SNAPCRAFT_IMAGE_INFO='{"test-var": "value"}'
@@ -36,3 +28,10 @@ execute: |
 
   cp manifest_0.1_*.snap ~
   review-tools.snap-review ~/manifest_0.1_*.snap
+restore: |
+  # The regular clean can potentially fail depending on if/when the test itself failed, but
+  # they should always both be attempted
+  snapcraft clean || true
+  snapcraft clean --destructive-mode
+  rm -f ./*.snap
+  rm -f ~/manifest_0.1_*.snap
