extensions: don't fail during installation
Currently, snapd doesn't connect automatically the plug for
gnome-42-2204, which means that, during installation, all the files
contained there aren't available. One of that files is fc-cache,
used in the 'configuration' hook to update the fonts.

This patch checks wether it is available or not before trying to
execute it, thus avoiding the failure during installation.

diff --git a/extensions/fonts/hooks-configure-fonts b/extensions/fonts/hooks-configure-fonts
--- a/extensions/fonts/hooks-configure-fonts
+++ b/extensions/fonts/hooks-configure-fonts
@@ -40,6 +40,14 @@ EOF
 
 export FONTCONFIG_FILE="${SNAP_COMMON}/fontconfig/fonts.conf"
 
-"${SNAP_DESKTOP_RUNTIME}/usr/bin/fc-cache" --force --system-only --verbose || echo "configure hook: font generation failed"
+if [ -f "${SNAP_DESKTOP_RUNTIME}/usr/bin/fc-cache" ]; then
+  "${SNAP_DESKTOP_RUNTIME}/usr/bin/fc-cache" --force --system-only --verbose || echo "configure hook: font generation failed"
+else
+  echo "Couldn't generate fonts because fc-cache is not available"
+fi
 
-exec "$@"
+if [ -f $1 ]; then
+  exec "$@"
+else
+  echo "Can't execute command $1 in hooks-configure-fonts"
+fi
