spread: improve resilience of lxd-type-base test
This test often times out on `lxc stop` on Google runners.

diff --git a/tests/spread/providers/lxd-type-base/task.yaml b/tests/spread/providers/lxd-type-base/task.yaml
--- a/tests/spread/providers/lxd-type-base/task.yaml
+++ b/tests/spread/providers/lxd-type-base/task.yaml
@@ -24,4 +24,14 @@ execute: |
 
   /snap/bin/lxc start snapcraft-core20
   /snap/bin/lxc exec snapcraft-core20 cat /etc/os-release | MATCH "VERSION_CODENAME=focal"
-  /snap/bin/lxc stop snapcraft-core20
+  
+  # Retry stopping, as on the Google runners this sometimes times out due to system load.
+  for i in {1..5}; do
+    /snap/bin/lxc stop --timeout 60 snapcraft-core20 && break || sleep 5
+  done
+  
+  # If the last stop failed, include the LXC logs in the output to establish why.
+  if [[ $? != 0 ]]; then
+    lxc info --show-log snapcraft-core20
+    exit 1
+  fi
