linting

diff --git a/tests/spread/providers/lxd-type-base/task.yaml b/tests/spread/providers/lxd-type-base/task.yaml
--- a/tests/spread/providers/lxd-type-base/task.yaml
+++ b/tests/spread/providers/lxd-type-base/task.yaml
@@ -26,12 +26,11 @@ execute: |
   /snap/bin/lxc exec snapcraft-core20 cat /etc/os-release | MATCH "VERSION_CODENAME=focal"
   
   # Retry stopping, as on the Google runners this sometimes times out due to system load.
-  for i in {1..5}; do
-    /snap/bin/lxc stop --timeout 60 snapcraft-core20 && break || sleep 5
-  done
-  
-  # If the last stop failed, include the LXC logs in the output to establish why.
-  if [[ $? != 0 ]]; then
+  for _ in {1..4}; do
+    sleep 5
+    /snap/bin/lxc stop --timeout 60 snapcraft-core20 && break
+  done || (
+    # If the last stop failed, include the LXC logs in the output to establish why.
     lxc info --show-log snapcraft-core20
     exit 1
-  fi
+  )
