requirements: update craft-parts to 1.19.7 (#4305)
Craft Parts 1.19.7 addresses issues related to version being set
twice during rebuilds.

Signed-off-by: Claudio Matsuoka <claudio.matsuoka@canonical.com>
Co-authored-by: Callahan <callahan.kovacs@canonical.com>

diff --git a/tests/spread/core22/linters/linter-ros2-humble-mixed/task.yaml b/tests/spread/core22/linters/linter-ros2-humble-mixed/task.yaml
--- a/tests/spread/core22/linters/linter-ros2-humble-mixed/task.yaml
+++ b/tests/spread/core22/linters/linter-ros2-humble-mixed/task.yaml
@@ -10,4 +10,16 @@ execute: |
   test -f linter-ros2-humble-mixed_1.0_*.snap
 
   sed -n '/^Running linters/,/^Creating snap/p' < output.txt > linter_output.txt
-  diff -u linter_output.txt expected_linter_output.txt
+
+  # diff everything except the list of libraries
+  diff --ignore-matching-lines "^- library: lib" expected_linter_output.txt linter_output.txt
+
+  # `|| true` is used because grep will error if there is no output from the `diff` call
+  NUM_DIFFERENCES=$(diff expected_linter_output.txt linter_output.txt | grep --count "[<>]" || true)
+
+  # the list of unused libraries may change from time to time, so check the output is similar but not identical
+  if [[ $NUM_DIFFERENCES -gt 10 ]]; then
+    echo "Error: linter warnings are significantly different:"
+    diff --unified expected_linter_output.txt linter_output.txt
+    exit 1
+  fi
