Use a build parameter to avoid polluting userspace with an environment variable that's not relevant.

diff --git a/extensions/desktop/common/desktop-exports b/extensions/desktop/common/desktop-exports
--- a/extensions/desktop/common/desktop-exports
+++ b/extensions/desktop/common/desktop-exports
@@ -60,8 +60,8 @@ function is_subpath() {
   [ "${dir##$parent/}" != "$dir" ] && return 0 || return 1
 }
 
-if ! snapctl is-connected "$PLATFORM_SNAP"; then
-  echo "ERROR: not connected to the ${PLATFORM_SNAP} content interface."
+if ! snapctl is-connected "%PLATFORM_PLUG%"; then
+  echo "ERROR: not connected to the %PLATFORM_PLUG% content interface."
   exit 1
 fi
 
diff --git a/extensions/desktop/common/fonts b/extensions/desktop/common/fonts
--- a/extensions/desktop/common/fonts
+++ b/extensions/desktop/common/fonts
@@ -25,8 +25,8 @@ else
   ARCH="$SNAP_ARCH-linux-gnu"
 fi
 
-if ! snapctl is-connected "$PLATFORM_SNAP"; then
-  echo "ERROR: not connected to the ${PLATFORM_SNAP} content interface."
+if ! snapctl is-connected "%PLATFORM_PLUG%"; then
+  echo "ERROR: not connected to the %PLATFORM_PLUG% content interface."
   exit 1
 fi
 
