extensions: check that the platform snap is connected in desktop extensions and bail out if not (LP: #1915712)

diff --git a/extensions/desktop/common/fonts b/extensions/desktop/common/fonts
--- a/extensions/desktop/common/fonts
+++ b/extensions/desktop/common/fonts
@@ -25,6 +25,11 @@ else
   ARCH="$SNAP_ARCH-linux-gnu"
 fi
 
+if ! snapctl is-connected "$PLATFORM_SNAP"; then
+  echo "ERROR: not connected to the ${PLATFORM_SNAP} content interface."
+  exit 1
+fi
+
 append_dir LD_LIBRARY_PATH "$SNAP_DESKTOP_RUNTIME/lib/$ARCH"
 append_dir LD_LIBRARY_PATH "$SNAP_DESKTOP_RUNTIME/usr/lib/$ARCH"
 append_dir LD_LIBRARY_PATH "$SNAP_DESKTOP_RUNTIME/usr/lib"
