fix(spread): set expected failures for core24 tests
This commit does the equivalent of pytest's "xfail(strict=True)": all
core24 tests are currently fail because no Snapcraft command has been
implemented yet, so the test checks that the tool fails with the
expected message, and then exits successfully.

The idea is that once a command is implemented the corresponding spread
tests will start to fail - we can then scrutinize each test to validate
the new behavior.

diff --git a/tests/spread/core24/scriptlets/scriptlet-failures/task.yaml b/tests/spread/core24/scriptlets/scriptlet-failures/task.yaml
--- a/tests/spread/core24/scriptlets/scriptlet-failures/task.yaml
+++ b/tests/spread/core24/scriptlets/scriptlet-failures/task.yaml
@@ -1,11 +1,14 @@
 summary: Validate scriptlet failures
 
-restore: |
-  snapcraft clean
+restore: |  # If this next line fails, delete it and replace it with the one following it
+  snapcraft clean 2>&1 | MATCH '"clean" command is not implemented for core24!'; exit 0
+  # snapcraft clean
   rm -f ./*.snap
 
 execute: |
-  snapcraft_log="$(snapcraft build 2>&1 || true)"
+  # If this next line fails, delete it and replace it with the one following it
+  snapcraft build 2>&1 | MATCH '"build" command is not implemented for core24!'; exit 0
+  # snapcraft_log="$(snapcraft build 2>&1 || true)"
 
   echo "${snapcraft_log}" | NOMATCH "^should have failed set-version"
   echo "${snapcraft_log}" | NOMATCH "^should have failed build"
